### ISSUE TITLE
convertkubeconfig expects acre.yaml

### ISSUE THREAD

**Issue by afritzler** [gardener/sow#8]
Currently the `convertkubeconfig` commad expects a valid `acre.yaml` to be present in the landscape project. Shouldn't the kubeconfig converion also work if e.g. it is provided via setting `KUBECONFIG`?

**Comment by Diaphteiros** [comment]
Environment variables are problematic, because `sow` is most probably executed inside a docker container with a complete different set of environment variables ...

**Comment by afritzler** [comment]
Good point!

**Comment by afritzler** [comment]
I guess then we can close this one.
